# Generated by Django 4.1 on 2022-10-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../media/users/profile_pics/default.jpg', upload_to='users/profile_pics/'),
        ),
    ]
