# Generated by Django 4.1 on 2022-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201118_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.IntegerField(default=0)),
                ('students', models.TextField(default='user')),
            ],
        ),
    ]
