# Generated by Django 4.1 on 2022-10-15 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201127_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignment',
            name='turned_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
